name: ggflutter_starter
description: 现代化Flutter脚手架，适合开源和企业级应用
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  provider: ^6.0.5
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  logger: ^2.0.2+1
  go_router: ^13.2.0
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/gg_icon.png"
