name: vending_machine_control
description: 自动售货机串口控制应用
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 串口通信
  flutter_serial_communication: ^0.1.0
  
  # UI组件
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # 网络请求
  dio: ^5.3.2
  
  # 状态管理
  provider: ^6.0.5
  
  # 本地存储
  shared_preferences: ^2.2.0
  
  # 权限管理
  permission_handler: ^10.4.3
  
  # 设备信息
  device_info_plus: ^9.0.3
  
  # 日志
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 