name: Build APK

on:
  push:
    tags:
      - 'v*.*.*'
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Remove old Flutter
      run: sudo rm -rf /opt/hostedtoolcache/flutter
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Install Flutter
      uses: flutter-actions/setup-flutter@v2
      with:
        version: '3.24.0'

    - name: Check Flutter & Dart version
      run: flutter --version
    
    - name: Install dependencies
      run: flutter pub get

    - name: Generate launcher icons
      run: flutter pub run flutter_launcher_icons:main
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ggflutter-starter-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
        tag_name: ${{ github.ref_name }}
        name: GGFlutter Starter v${{ github.ref_name }}
        body: |
          ## GGFlutter Starter
          
          ### 主要特性
          - 一键配置项目名、包名、App 名称、Logo
          - 丰富通用功能演示
          - Android/iOS 双端支持
          - 现代化UI设计
          
          ### 安装说明
          1. 下载APK文件
          2. 在Android设备上启用"未知来源"应用安装
          3. 安装APK文件
          
          ### 系统要求
          - Android 5.0+ (API 21)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 